### ISSUE TITLE
O aplicativo encerra ao tentar interagir na aba de coleções

### ISSUE THREAD

**Issue by maxaraujo** [olmps/memo#131]
**Descreva o Bug/Describe the bug:**
O aplicativo encerra ao tentar interagir na aba de coleções

**Passos para Reproduzir/Steps to Reproduce:**

1. Abra o app
2. Entre na tela Coleções
3. Tente usar o scroll ou clicar em algum curso

**Resultado Esperado/Expected Result:**

Entrar em um curso ou rolar a página para ver mais cursos

**Resultado Obtido/Actual Result:**

Aplicativo fecha.

**Screenshots:**

![VID_20210717_131944054](https://user-images.githubusercontent.com/19292942/126043642-714712e3-0335-4070-a025-c3f756838dba.gif)

**Versão do app/App Version:**

App baixado da google play store na versão 0.1.0
Problema acontece em um Tablet Samsung Tab A - SM-T510
Versão do Android: 11

**Comment by matuella** [comment]
Muito obrigado por abrir a issue @maxaraujo

Iremos investigar mais a fundo o que está acontecendo para tentar solucionar o problema!

Abaixo segue o crash log e possíveis issues relacionadas a sua causa.

<details>
  <summary>Firebase Crash Logs</summary>

```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.olmps.memoClient/com.example.memo.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.olmps.memoClient/com.example.memo.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)


Caused by java.lang.RuntimeException
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
Caused by java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java)
       at android.app.Activity.performCreate(Activity.java:6699)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)


Caused by java.util.concurrent.ExecutionException
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at java.util.concurrent.FutureTask.report(FutureTask.java:94)
       at java.util.concurrent.FutureTask.get(FutureTask.java:164)
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java)
       at android.app.Activity.performCreate(Activity.java:6699)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6124)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)


Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.olmps.memoClient-1/base.apk"],nativeLibraryDirectories=[/data/app/com.olmps.memoClient-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1001)
       at java.lang.System.loadLibrary(System.java:1562)
       at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

```
</details>

Possible related issues:
- https://github.com/flutter/flutter/issues/78285
- https://github.com/flutter/flutter/issues/64697

**Comment by ggirotto** [comment]
Oi @maxaraujo . Você consegue nos confirmar se vocês moveu o app para o seu cartão SD externo antes de abrir ele? Estamos investigando ainda as causas desse crash.

Related issues:
- https://stackoverflow.com/questions/52595535/using-an-app-bundle-i-get-unsatisfiedlinkerror-for-1-of-users

**Comment by maxaraujo** [comment]
Oi @ggirotto. Não. Apenas instalei e tentei usar o app.
